config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'top#index'
  resources :posts, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :tags, only: %i[index show]
  resources :about, only: %i[index]

  namespace :admin do
    root 'home#index'
    resources :posts, only: %i[new create edit update destroy] do
      get :all, :published, :drafts, on: :collection
    end
    resources :categories, only: %i[index show create]
    resources :photos, only: %i[index create]
  end

  get '*path', to: 'application#render_404' if Rails.env.production?
end

app/views/shared/_admin_side.html.erb
<div class="admin-side">
  <div class="admin-side--header">
    <%= fa_icon "home" %><%= link_to 'hirozak', root_path, target: "_blank" %>
  </div>
  <div class="admin-side--menu">
    <ul>
      <li class="admin-side--menu_item">
        <%= fa_icon "bar-chart" %><%= link_to "Dashboard", admin_root_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= fa_icon "pencil-square-o" %><%= link_to "New Post", new_admin_post_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= fa_icon "file-code-o" %><%= link_to "All Posts", all_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item__sub">
        <%= link_to "- Published", published_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item__sub">
        <%= link_to "- Drafts", drafts_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= fa_icon "tags" %><%= link_to "Category", admin_categories_path %>
      </li>
      <!-- <li class="admin-side--menu_item">
        <%= fa_icon "hashtag" %><%= link_to "Tag", "#" %>
      </li> -->
      <li class="admin-side--menu_item">
        <%= fa_icon "sign-out" %><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>©Copyright 2019 hirozak.All Rights Reserved.</p>
</footer>

app/views/shared/_header_image.html.erb
<div class="top-header">
  <%= image_tag 'top-header', class: "top-header--image hidden-xs" %>
  <%= image_tag 'top-header-xs', class: "top-header--image visible-xs" %>
</div>

app/views/shared/_header_menu.html.erb
<div class="top-menu">
  <div class="container-fluid">
    <table class="top-menu--list">
      <tr>
        <th><%= link_to "All", posts_path, class: "top-menu--list-item" %></th>
        <th><%= link_to "Life", category_path("Life"), class: "top-menu--list-item" %></th>
        <th><%= link_to "Gadgets", category_path("Gadgets"), class: "top-menu--list-item" %></th>
        <th><%= link_to "Tech", category_path("tech"), class: "top-menu--list-item" %></th>
        <th><%= link_to "Music", category_path("Music"), class: "top-menu--list-item" %></th>
        <th><%= link_to "About".html_safe, "../about", class: "top-menu--list-item" %></th>
      </tr>
    </table>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-default navbar-all">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="top-title">
        <%= link_to 'hirozak', root_path, class: "top-title-link" %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right navbar-links">
        <li><%= link_to 'Categories', categories_path, class: "navbar-link" %></li>
        <li><%= link_to 'Tags', tags_path, class: "navbar-link" %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle navbar-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ログイン中 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'admin', admin_root_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_post_list.html.erb
<header>
  <%= render 'shared/navbar' %>
  <%= render 'shared/header_image' %>
  <%= render 'shared/header_menu' %>
  <div class="container-fluid slider-container">
    <div class="post-slider">
      <% @slider_posts.each do |slide_post| %>
        <div class="post-slider--item">
          <%= link_to slide_post do %>
            <%= image_tag slide_post.image.url(:thumb), class:"post-slider--item_image" %>
            <div class="post-slider--item_title">
              <%= slide_post.title %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>
<div class="main-wrapper">
  <div class="container-fluid main-container">
    <div class="posts-wrapper">
      <div class="posts">
        <h2 class="main-title"><%= main_title %></h2>
        <div class="posts-wrapper">
          <%= render partial: 'shared/post', collection: @posts %>
        </div>
        <div class="posts-pagination">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/sub_content' %>
<%= render 'shared/footer' %>

app/views/shared/_sub_content.html.erb
<div class="sub-wrapper">
  <div class="container-fluid sub-container">
    <div class="row sub">
      <div class="col-md-8 col-xs-12 profile">
        <h2 class="profile-title">About Me</h2>
        <div class="col-md-5 col-sm-5 col-xs-5 profile-image">
          <%= image_tag 'profile-image', class: "profile-image--item" %>
        </div>
        <div class="col-md-7 col-sm-7 col-xs-7 profile-info">
          <p class="profile-info--name">hirozak</p>
          <div class="profile-info--link">
            <%= link_to "https://twitter.com/xringoxr", {class: "profile-info--sns icon-sns icon-twitter", target: "_blank"} do %>
              <%= fa_icon "twitter 2x" %>
            <% end %>
            <%= link_to "https://www.instagram.com/hirozak/", {class: "profile-info--sns icon-sns icon-instagram", target: "_blank"} do %>
              <%= fa_icon "instagram 2x" %>
            <% end %>
            <%= link_to "https://github.com/hirozak", {class: "profile-info--sns icon-sns icon-github", target: "_blank"} do %>
              <%= fa_icon "github 2x" %>
            <% end %>
          </div>
          <div class="profile-info--description">
            <p>エンジニア</p>
            <p>音楽, 映画, 海外ドラマ, ガジェット, インテリア, お酒が好きです。</p>
            <%= link_to "詳しく見る", "../about", class: "btn btn-outline-default btn-round" %>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-xs-12 this_blog">
        <h2 class="this_blog-title">This Blog</h2>
        <div class="this_blog-description">
          <p>このブログはhirozakがRuby on Railsで開発しました。</p>
          <p>GitHubにて、ソースコードを公開しています。</p>
          <div class="this_blog-description--link">
            <div class="blogCard blogCard--noimg">
              <div class="blogCardCont">
                <div class="blogCardTxt">
                  <p class="blogCardTitle"><a href="https://github.com/hirozak/hirozak.space" target="_blank">hirozak/hirozak.space</a></p>
                  <p>hirozak.space - my blog</p>
                </div>
              </div>
              <div class="blogCardFooter">
                <a href="https://github.com/hirozak/hirozak.space"><img src="https://github.githubassets.com/pinned-octocat.svg" alt="">github.com</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>