config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'top#index'
  resources :posts, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :tags, only: %i[index show]
  resources :about, only: %i[index]

  namespace :admin do
    root 'home#index'
    resources :posts, only: %i[new create edit update destroy] do
      get :all, :published, :drafts, on: :collection
    end
    resources :categories, only: %i[index show create]
    resources :photos, only: %i[index create]
  end

  get '*path', to: 'application#render_404' if Rails.env.production?
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true

  def to_param
    name
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_categories

  def index
    @category = Category.new
  end

  def show
    @category = Category.find_by(name: params[:id])
    @posts = @category.posts.includes(:category).default_order.page(params[:page]).per(8)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: 'カテゴリを作成しました。'
    else
      flash.alert = 'カテゴリーの作成に失敗しました。'
      render :index
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(name: params[:id])
    @posts = @category.posts.published.default_order.page(params[:page]).per(12) if @category.posts
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/views/admin/categories/_category.html.erb
<div class="col-md-4 category">
  <%= link_to admin_category_path(category) do %>
    <h2><%= category.name %>(<%= category.posts.count %>)</h2>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<% set_meta_tags noindex: true %>
<script>
  $(function() {
    $("html").addClass("admin-wrap");
    $("body").addClass("admin-wrap");
    $(".wrap").addClass("admin-wrap");
  })
</script>
<div class="admin">
  <%= render 'shared/admin_side' %>
  <div class="admin-main">
    <div class="admin-main--header">
      <h2>Categories</h2>
    </div>
    <div class="admin-main--body">
      <div class="row categories">
        <%= render @categories %>
      </div>
      <div class="row categories">
        <div class="col-md-6 category-new">
          <div class="form-group">
            <%= form_for [:admin, @category] do |f| %>
              <div class="col-sm-10 category-new--form">
                <%= f.text_field :name, class:"col-sm-10 form-control input-lg" %>
              </div>
              <%= button_tag type: 'submit', class:"btn btn-primary col-sm-2" do %>
                <%= fa_icon "plus-square-o 2x" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% set_meta_tags noindex: true %>
<%= render "admin/posts/post_list", title: @category.name %>